### PR TITLE
Chore: prepare release

### PR DESCRIPTION
**Pull request by lukaswagner**

### CODE REVIEW

**Comment by lukaswagner** [comment]
@XR4Z0R is there a reason for using v4 of framer-motion instead of v5? From what I can see with `npm why framer-motion`, all packages that require this as a peer dependency are ok with v5 as well.

**Comment by XR4Z0R** [comment]
`framer-motion` is used by Chakra UI, which I used as components library for the test app. When I initialized the project, the documentation page used explicitly v4 in their install command. I just checked the documentation now and it says `framer-motion@^5`, so I guess updating to v5 is fine.

**Comment by lukaswagner** [comment]
Ok, thanks! I'll update it and try it out.

**Comment by lukaswagner** [comment]
@XR4Z0R I've played around with `np` a bit and it seems like a nice tool. My only issue right now is that `np` insists on bumping the version number. This would break the apps' dependecy notations. Do you have any experience with this issue?

I'd propose bumping all deps manually before bumping the lib using `np`. For the initial release, this would mean setting the lib version back down to 0.0.0 so `np` can bump it to `0.1.0`. This workflow doesn't seem optimal though.

**Comment by XR4Z0R** [comment]
Actually, I didn't work with `np` yet. So I was not aware of this problem. In another monorepo project, I used Lerna as monorepo management tool, which handles bumping all versions of depending packages automatically.

But for the initial release: `np` allows giving an explicit version as argument. So you might be able to run `np 0.1.0` for the correct version (without adapting the `package.json`)?

**Comment by lukaswagner** [comment]
That was my first idea as well, sadly `np` does not accept this:

image

**Comment by XR4Z0R** [comment]
Then I guess you have to change the version to `0.0.0`. This is also the procedure `np` is suggesting in their readme:
> For new packages, start the version field in package.json at 0.0.0 and let np bump it to 1.0.0 or 0.1.0 when publishing.

Also, I noticed: Since this package is scoped (with `@lukaswagner`) you have to adjust the `package.json`:
> To publish scoped packages to the public registry, you need to set the access level to public. You can do that by adding the following to your package.json:
```json
"publishConfig": {
    "access": "public"
}
```

**Review by XR4Z0R — APPROVED** [review]

**Pull request merged**
